export const actionType = {
  GET_PASSENGERS: 'GET_PASSENGERS',
  GET_TOTAL_ALL_PAGES: 'GET_TOTAL_ALL_PAGES',
  GET_PASSENGER_ID: 'GET_PASSENGER_ID',
  GET_PAGE_SIZE: 'GET_PAGE_SIZE',
  SET_CONDITION_STATIC: 'SET_CONDITION_STATIC',
  GET_FILTERS: 'GET_FILTERS',
  STATUS_LOGIN: 'STATUS_LOGIN'
}